<ul class="nav nav-tabs card-header-tabs">
    <li class="nav-item">
        <a class="nav-link <?= $current == 'register' ? 'active' : '' ?>"
           href="/">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= $current == 'login' ? 'active' : '' ?>"
           href="/login">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= $current == 'password-restore-request' ? 'active' : '' ?>"
           href="/password-restore-request">Password Restore</a>
    </li>
</ul>