<?php declare(strict_types=1);

/** @var $data array */
/** @var $errors array */

$this->layout('layout', ['title' => 'Password Restore']);

$formFields = [
    'identity' => ['Login or e-mail', 'text', 'Login/e-mail is correct'],
];
?>
<form method="post" action="/password-restore-request">
    <?= $this->csrf('/password-restore-request') ?>
    <div class="card">
        <div class="card-header">
            <?php $this->insert('user/guest/nav', ['current' => 'password-restore-request']) ?>
        </div>
        <div class="card-body">
            <?php foreach ($formFields as $alias => $parts):
                [$label, $type, $correctMsg] = $parts ?>
                <div class="form-group row">
                    <label for="<?= $alias ?>" class="col-md-4 col-form-label"><?= $label ?></label>
                    <div class="col-md-8">
                        <input type="<?= $type ?>" id="<?= $alias ?>" name="<?= $alias ?>" required
                               value="<?= $this->e($data[$alias] ?? '') ?>"
                               class="form-control <?= isset($errors[$alias]) ? 'is-invalid' : '' ?>">
                        <div class="<?= isset($errors[$alias]) ? 'invalid-feedback' : 'valid-feedback' ?>">
                            <?= $this->e($errors[$alias] ?? $correctMsg) ?>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>

            <div class="form-group row">
                <label for="captcha" class="col-md-4 col-form-label">Enter Captcha</label>
                <div class="col-md-4">
                    <input type="text" id="captcha" name="captcha" required
                           class="form-control <?= isset($errors['captcha']) ? 'is-invalid' : '' ?>">
                    <div class="<?= isset($errors['captcha']) ? 'invalid-feedback' : 'valid-feedback' ?>">
                        <?= $this->e($errors['captcha'] ?? 'Captcha is correct') ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="/captcha" class="captcha" id="captcha-img" alt="Captcha image">
                    <small class="form-text text-muted">
                        <a href="javascript:void(0);"
                           onclick="document.getElementById('captcha-img').src='/captcha?r=' + new Date().getTime();"
                        >Refresh</a>
                    </small>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" name="restore" class="btn btn-primary">Restore</button>
                </div>
            </div>
        </div>
    </div>
</form>