<?php declare(strict_types=1);

/** @var $user array */

$this->layout('layout', ['title' => 'Profile']);

$profileFields = [
    'login' => 'Login',
    'email' => 'E-mail',
    'full_name' => 'Full Name',
    'registered_at' => 'Registered At'
];
?>
<div class="card">
    <div class="card-header">
        <?php $this->insert('user/profile/nav', ['current' => 'profile']) ?>
    </div>
    <div class="card-body">
        <table class="table border-bottom">
            <tbody>
                <?php foreach ($profileFields as $alias => $label): ?>
                <tr>
                    <th><?= $label ?></th>
                    <td><?= $this->e($user[$alias]) ?></td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>

        <a href="/logout" class="btn btn-outline-secondary">Logout</a>
    </div>
</div>
