<ul class="nav nav-tabs card-header-tabs">
    <li class="nav-item">
        <a class="nav-link <?= $current == 'profile' ? 'active' : '' ?>"
           href="/profile">Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= $current == 'profile-edit' ? 'active' : '' ?>"
           href="/profile-edit">Change Full Name</a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= $current == 'password-change' ? 'active' : '' ?>"
           href="/password-change">Change Password</a>
    </li>
</ul>